### ISSUE TITLE
Refactoring using react

### ISSUE THREAD

**Issue by fernandodrcampos** [lucas231090/escolas#1]
I'm trying upgrade the project using React, how can I do it?

**Comment by lucas231090** [comment]
First you need to install NodeJS and React globally on your machine. After that create your first React Create App and code.
Remember that React uses JSX

**Comment by fernandodrcampos** [comment]
> First you need to install NodeJS and React globally on your machine. After that create your first React Create App and code. Remember that React uses JSX

I'll try thanks

**Comment by fernandodrcampos** [comment]
@lucas231090 i'm done

**Comment by lucas231090** [comment]
WpooooooooooW. sharing with me. Congrats

**Comment by fernandodrcampos** [comment]
> WpooooooooooW. sharing with me. Congrats

done.
